name: Deployment

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to create a release on the repository
    steps:
      - uses: actions/checkout@v4

      - name: Find git branch name
        run: |
          git_branch_name=$(git branch --contains refs/tags/${GITHUB_REF_NAME} | grep -v "detached" | head -n 1 | sed 's/^[* ] //')
          echo "git_branch_name=$git_branch_name" >> $GITHUB_ENV

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # validate gradle wrapper signature
      - uses: gradle/actions/wrapper-validation@v3

      # Gradle caching and more
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: "${{ github.event.repository != null && env.git_branch_name != format('refs/heads/{0}', github.event.repository.default_branch) }}"

      # perform the gradle build
      - name: Execute Gradle Build
        run: ./gradlew build publish github --stacktrace -Porg.gradle.parallel.threads=4
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
